### ISSUE TITLE
combine_words seems to be broken

### ISSUE THREAD

**Issue by Qwarr** [britzl/defold-richtext#81] opened 2023-02-11 02:15 UTC
```lua
	local text = "This whole message"
	
	local settings = {
		fonts = {
			pixel = {
				regular = hash("system_font_df"),
			},
		},
		size = 1.25,
		width = 900,
		parent = gui.get_node("center"),
		position = vmath.vector3(0, 0, 0),
		align = richtext.ALIGN_CENTER,
		combine_words = true 
	}
	
	self.rt_text = richtext.create(text, "pixel", settings)
```
![2023-02-10 18_13_50-Window](https://user-images.githubusercontent.com/2577547/218233850-b70127d5-73eb-4b96-9f8c-c9c4147f6085.png)
![2023-02-10 18_14_04-Window](https://user-images.githubusercontent.com/2577547/218233853-8067960f-38bb-4fcd-9d24-690e93e43125.png)

	
When I have combine_words = true then the message gets squished together.

**Comment by britzl** [comment] 2023-02-12 12:28
Sorry, regression caused by recent changes. Fixed in https://github.com/britzl/defold-richtext/commit/4ba32ac78429aaaf0bc141ee6d932e0d5b912380

**Closed by britzl** 2023-02-12 12:28 UTC
